#pragma once

/*
* DO NOT MAKE CHANGES INTO THIS FILE.
* CONTENT IS AUTOGENERATED BY THE BUILD SYSTEM.
*/

namespace Engine
{
    static const size_t MAJOR_VERSION = 1;
    static const size_t MINOR_VERSION = 2;
    static const char* VERSION_STRING = "version1.2";
}