#pragma once
#include <stdint.h>

/*
* DO NOT MAKE CHANGES INTO THIS FILE.
* CONTENT IS AUTOGENERATED BY THE BUILD SYSTEM.
*/

namespace Engine
{
    constexpr const size_t MAJOR_VERSION = 1;
    constexpr const size_t MINOR_VERSION = 0;
    constexpr const char* VERSION_STRING = "version1.0";
}