#pragma once

/*
* DO NOT MAKE CHANGES INTO THIS FILE.
* CONTENT IS AUTOGENERATED BY THE BUILD SYSTEM.
*/

namespace Engine
{
    const size_t MAJOR_VERSION = 1;
    const size_t MINOR_VERSION = 1;
    const char* VERSION_STRING = "version1.1";
}